name: location_report
description: "a location-based reporting mobile app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  objectbox: ^4.3.0
  objectbox_flutter_libs: any
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  google_maps_flutter: ^2.12.3
  go_router: ^16.0.0
  flutter_svg: ^2.2.0
  location: ^8.0.1
  image: ^4.5.4
  path_provider: ^2.1.5
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  path: ^1.9.1
  intl: ^0.20.2
  rxdart: ^0.28.0
  fluttertoast: ^8.2.12
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  objectbox_generator: any

objectbox:
  output_dir: generated

flutter:

  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/icons/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik_variable.ttf

